language: node_js
node_js:
  - "8"
sudo: required
before_install:
  - npm install -g node-gyp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  - CXX=g++-4.8
script:
 - npm install
 - npm test
after_success: 'npm run coveralls' 

