language: node_js
node_js:
  - "8"
sudo: required
before_install:
  - npm install -g node-gyp
cache:
  directories:
  - node_modules
addons:
  - postgresql: "9.4"
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  - CXX=g++-4.8
global:
  - export NODE_ENV=test
script:
 - npm run test
after_success: 
  - codeclimate-test-reporter < coverage/lcov.info
  - npm run coverage
  - npm run coveralls
services:
  - postgresql
before_script:
 - psql -c "CREATE DATABASE \"events_test\";" -U postgres
 - npm install
 - npm install -g sequelize-cli

