language: node_js

node_js:
  - "8.11.1"

script:
  - NODE_ENV=test npm run pretest
  - NODE_ENV=development npm run pretest

install:
  - npm install
  - npm install -g codecov
env:
  

services:
  - postgresql

cache:
  directories:
   - "node_modules"

before_script:
  - psql -c "create database events_test;" -U postgres
  - psql -c "create database events_dev;" -U postgres

after_success:
  - NODE_ENV=development npm run coverage
  - NODE_ENV=test npm run coverage
  - npm run jest

