// user actions
export const REGISTER_USER = 'register_user';
export const LOGIN_USER = 'login_user';
export const LOGOUT_USER = 'Logout_user';

// center actions
export const IS_CENTER_CREATING = 'IS_CENTER_CREATING';
export const CREATE_CENTER_SUCCESS = 'CREATE_CENTER_SUCCESS';
export const CREATE_CENTER_FAILURE = 'CREATE_CENTER_FAILURE';
export const IS_CENTERS_FETCHING = 'IS_CENTERS_FETCHING';
export const FETCH_CENTERS_SUCCESS = 'FETCH_ALL_CENTERS_SUCCESS';
export const FETCH_CENTERS_FAILURE = 'FETCH_ALL_CENTERS_FAILURE';
export const IS_CENTER_UPDATING = 'IS_CENTER_UPDATING';
export const UPDATE_CENTER_SUCCESS = 'UPDATE_CENTER_SUCCESS';
export const UPDATE_CENTER_FAILURE = 'UPDATE_CENTER_FAILURE';
export const IS_CENTER_DELETING = 'IS_CENTER_DELETING';
export const DELETE_CENTER_SUCCESS = 'DELETE_CENTER_SUCCESS';
export const DELETE_CENTER_FAILURE = 'DELETE_CENTER_FAILURE';

// event actions
export const IS_EVENT_CREATING = 'IS_EVENT_CREATING';
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';
export const CREATE_EVENT_FAILURE = 'CREATE_EVENT_FAILURE';
export const IS_USER_EVENTS_FETCHING = 'IS_USER_EVENTS_FETCHING';
export const FETCH_USER_EVENTS_SUCCESS = 'FETCH_USER_EVENTS_SUCCESS';
export const FETCH_USER_EVENTS_FAILURE = 'FETCH_USER_EVENTS_FAILURE';
export const IS_EVENT_UPDATING = 'IS_EVENT_UPDATING';
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS';
export const UPDATE_EVENT_FAILURE = 'UPDATE_EVENT_FAILURE';
export const IS_EVENT_DELETING = 'IS_EVENT_DELETING';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';
export const DELETE_EVENT_FAILURE = 'DELETE_EVENT_FAILURE';

