// user actions
export const REGISTERING_USER = 'REGISTERING_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const IS_USERS_FETCHING = 'IS_USERS_FETCHING';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';
export const IS_USER_SETTING = 'IS_USER_SETTING';
export const SET_USER_SUCCESS = 'SET_USER_SUCCESS';
export const SET_USER_FAILURE = 'SET_USER_FAILURE';
export const IS_USER_DELETING = 'IS_USER_DELETING';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

// center actions
export const IS_CENTER_CREATING = 'IS_CENTER_CREATING';
export const CREATE_CENTER_SUCCESS = 'CREATE_CENTER_SUCCESS';
export const CREATE_CENTER_FAILURE = 'CREATE_CENTER_FAILURE';
export const IS_CENTERS_FETCHING = 'IS_CENTERS_FETCHING';
export const FETCH_CENTERS_SUCCESS = 'FETCH_ALL_CENTERS_SUCCESS';
export const FETCH_CENTERS_FAILURE = 'FETCH_ALL_CENTERS_FAILURE';
export const IS_CENTER_UPDATING = 'IS_CENTER_UPDATING';
export const UPDATE_CENTER_SUCCESS = 'UPDATE_CENTER_SUCCESS';
export const UPDATE_CENTER_FAILURE = 'UPDATE_CENTER_FAILURE';
export const IS_CENTER_DELETING = 'IS_CENTER_DELETING';
export const DELETE_CENTER_SUCCESS = 'DELETE_CENTER_SUCCESS';
export const DELETE_CENTER_FAILURE = 'DELETE_CENTER_FAILURE';
export const GET_CENTER_DETAILS = 'GET_CENTER_DETAILS';
export const IS_CENTER_FETCHING = 'IS_CENTER_FETCHING';
export const FETCH_CENTER_SUCCESS = 'FETCH_CENTER_SUCCESS';
export const FETCH_CENTER_FAILURE = 'FETCH_CENTER_FAILURE';
export const CLEAR_CENTER_STATE = 'CLEAR_CENTER_STATE';

// event actions
export const IS_EVENT_CREATING = 'IS_EVENT_CREATING';
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';
export const CREATE_EVENT_FAILURE = 'CREATE_EVENT_FAILURE';
export const IS_USER_EVENTS_FETCHING = 'IS_USER_EVENTS_FETCHING';
export const FETCH_USER_EVENTS_SUCCESS = 'FETCH_USER_EVENTS_SUCCESS';
export const FETCH_USER_EVENTS_FAILURE = 'FETCH_USER_EVENTS_FAILURE';
export const IS_EVENT_UPDATING = 'IS_EVENT_UPDATING';
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS';
export const UPDATE_EVENT_FAILURE = 'UPDATE_EVENT_FAILURE';
export const IS_EVENT_DELETING = 'IS_EVENT_DELETING';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';
export const DELETE_EVENT_FAILURE = 'DELETE_EVENT_FAILURE';
export const IS_EVENT_CANCELING = 'IS_EVENT_CANCELING';
export const CANCEL_EVENT_SUCCESS = 'CANCEL_EVENT_SUCCESS';
export const CANCEL_EVENT_FAILURE = 'CANCEL_EVENT_FAILURE';
export const IS_EVENTS_FETCHING = 'IS_EVENTS_FETCHING';
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
export const FETCH_EVENTS_FAILURE = 'FETCH_EVENTS_FAILURE';
export const IS_USER_HISTORY_FETCHING = 'IS_USER_HISTORY_FETCHING';
export const FETCH_USER_HISTORY_SUCCESS = 'FETCH_USER_HISTORY_SUCCESS';
export const FETCH_USER_HISTORY_FAILURE = 'FETCH_USER_HISTORY_FAILURE';
export const IS_CENTER_EVENTS_FETCHING = 'IS_CENTER_EVENTS_FETCHING';
export const FETCH_CENTER_EVENTS_SUCCESS = 'FETCH_CENTER_EVENTS_SUCCESS';
export const FETCH_CENTER_EVENTS_FAILURE = 'FETCH_CENTER_EVENTS_FAILURE';
export const CLEAR_CENTER_EVENTS = 'CLEAR_CENTER_EVENTS';

